### ISSUE TITLE
Could you update to Python3.7.9

### ISSUE THREAD

**Issue by qiaofeng1227** [adrienverge/copr-python37#1]
The latest version: https://www.python.org/ftp/python/3.7.9/
Thanks

**Comment by adrienverge** [comment]
Sorry but no, I don't provide support for this COPR. However the good news is, the COPR content is open source: you can do it yourself.

**Comment by qiaofeng1227** [comment]
I'm glad to hear from you so soon.
I've forked your project




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adrienverge/copr-python37"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 下午3:27
收件人:&nbsp;"adrienverge/copr-python37"<copr-python37@noreply.github.com&gt;;
抄送:&nbsp;"徐伟"<76487013@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [adrienverge/copr-python37] Could you update to Python3.7.9 (#1)





 
Sorry but no, I don't provide support for this COPR. However the good news is, the COPR content is open source: you can do it yourself.
